version: "3.9"

services:
  freeformed:
    image: freeformed/freeformed:latest
    container_name: freeformed
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    # networks:
    #   - internal
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
      - minio:/root/.minio
    command: server /data --console-address ":9001"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: freeformed
      POSTGRES_PASSWORD: freeformed
      POSTGRES_DB: freeformed
    # networks:
    #   - internal
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    shm_size: 512mb
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "freeformed"]
    #   interval: 30s
    #   timeout: 20s
    #   retries: 3
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    # networks:
    #   - internal
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 5431:8080
    # networks:
    #   - internal

networks:
  internal:
    driver: bridge


volumes:
  minio: null
  postgres: null
  pgadmin:

  # minio:
  #   image: quay.io/minio/minio
  #   container_name: minio
  #   restart: always
  #   command: server /mnt/data --console-address ":9001" --certs-dir /mnt/certs
  #   expose:
  #     - "9000"
  #     - "9001"
  #   environment:
  #     MINIO_ROOT_USER: comnoco
  #     MINIO_ROOT_PASSWORD: comnoco_minio
  #   # healthcheck:
  #   #   test: ["CMD", "curl", "-I", "https://localhost:9000/minio/health/live"]
  #   #   interval: 30s
  #   #   timeout: 20s
  #   #   retries: 3
  #   ports:
  #     - 9001:9001
  #     - 9000:9000
  #   networks:
  #     - internal
  #   volumes:
  #     - minio:/mnt/data
  #     - ./ssl:/mnt/certs
